language: php

php:
  - 7.2
  - 7.3

env:
  - PHPCS=1 PHPUNIT=1

before_script:
  - composer install
  - sh -c "if [ '$PHPCS' = '1' ]; then composer global require squizlabs/php_codesniffer=*; fi"

script:
  - sh -c "if [ '$PHPUNIT' = '1' ]; then vendor/bin/phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then ~/.config/composer/vendor/bin/phpcs -p --extensions=php --standard=PSR2 --ignore=./src/Thirdparty/* ./src; fi"

notifications:
  email: false
